services:
  frontend:
    container_name: my-app-frontend
    build:
      context: frontend
      dockerfile: frontend/prod-without-multistage.Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - next-my-app-network

networks:
  next-my-app-network:
