services:
  frontend:
    container_name: my-app-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - next-my-app-network

networks:
  next-my-app-network:
